config:
  rcalib:
    board_frame_id: gridboard
    camera_frame_id: camera
    flange_frame_id: flange
    image_view:
      width: 640
      height: 512
  rguide:
    K: /rovi/left/remap/K

rguide:
  zratio: 1.2
  rpy: [0,0,0, 20,0,0, 0,20,-10, -20,0,0, 0,-20,10]
