config:
  rcalib:
    board_frame_id: gridboard
    camera_frame_id: camera
    flange_frame_id: flange
  rguide:
    K: /rovi/left/remap/K
    width: 150
    height: 100
    distance: [400,500,600]
    rpy: [0,0,0, 40,0,0, 0,40,-10, -40,0,0, 0,-40,10]