gridboard:
  bin_param0: 0
  bin_param1: 0
  bin_type: 1
  distance_between_circles: 1.2
  do_equalize_hist: 0
  do_smoothing: 1
  fitrange: 1.5
  fitscore: 0.95
  gamma_correction: 1.0
  max_rate: 2.0
  min_rate: 0.25
  n_circles_minimum: 9
  n_circles_x: 13
  n_circles_y: 18
  origin_x: 6
  origin_y: 9
  torelance: 1.5
  unitleng: 0.01
rguide:
  height: 100
  width: 150
  distance: 400
  zratio: 1.2
