config:
  searcher:
    solver: ransac_solver
    scenes: ["surface"]
    scene_frame_id: ["camera/capure0"]
    master_frame_id: ["camera/master0"]
    solve_frame_id: "camera/capture0"
  picker:
    multiplex: 1
    solve_frame_id: "camera/capture0"
