config:
  searcher:
    solver: km1_solver
    scenes: ["surface"]
    scene_frame_id: ["camera/capure0"]
    master_frame_id: ["camera/master0"]
    solve_frame_id: "camera/capture0"
    tf_delay: 0.1
