config_tf:
  J5:
    parent_frame_id: world
  J6:
    parent_frame_id: world
  flange:
    parent_frame_id: J6
  mount:
    parent_frame_id: J5
  camera:
    parent_frame_id: mount
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 0
        y: 0
        z: 0
