config_tf:
  J5:
    parent_frame_id: world
  J6:
    parent_frame_id: world
  camera:
    parent_frame_id: J5
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 0
        y: 0
        z: 0
  flange:
    parent_frame_id: J6
