config:
  launch:
    _1:
      package: rovi
      file: ycam3sxga_m.launch
      auto: 0
    _2:
      package: rovi_industrial
      file: demo.launch
      auto: 0
    _3:
      package: rovi_master_teach
      file: main.launch
      auto: 10
    _4:
      package: rovi_utils
      file: calib.launch
    _5:
      package: rovi_master_teach
      file: setup.launch
